config/routes.rb
Rails.application.routes.draw do
  root 'students#index'

  get 'year_with_most/men_percentage' => 'students#get_year_with_most_men_percentage'
  get 'women_students/most_popular_age' => 'students#get_women_students_with_most_popular_age'
  get 'women_students/most_popular_names' => 'students#get_most_popular_names_women'
  get 'men_students/most_popular_names' => 'students#get_most_popular_names_men'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = Student.all
    end

    def show
        @student = Student.find(params[:id])
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)

        if @student.save
            redirect_to @student
        else
            render :new
        end
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
      @student = Student.find(params[:id])
  
      if @student.update(student_params)
        redirect_to @student
      else
        render :edit
      end
    end
    
    def destroy
      @student = Student.find(params[:id])
      @student.destroy
  
      redirect_to root_path
    end

    def get_year_with_most_men_percentage
      @years = Student.distinct.pluck(:year)
      
      @percentage = 0
      @years_with_percentage = []

      @years.each do |year|
        puts year
        students_total = Student.group(:year).count[year]
        men = Student.select { |student| student.year == year && student.sex }.count
        value = 100.0*men/students_total
        puts value
        if value > @percentage
          @percentage = value
          @years_with_percentage = [year]
        elsif value == @percentage
          @years_with_percentage.push(year)
        end
      end
    end


    def get_women_students_with_most_popular_age
      women = Student.select {|student| !student.sex}

      count = Hash.new(0)

      women.each do |w|
        count[w.age] += 1
      end

      max_count = count.values.max
      ages = count.select {|age, count| age if count == max_count}


      @students = Student.select { |student| !student.sex && (ages.include? student.age) }.map { |s| get_name_initials(s) }.sort
    end

    def get_most_popular_names_men
      @students = get_most_popular_names(true)
    end

    def get_most_popular_names_women
      @students = get_most_popular_names(false)
    end

    private
    def get_most_popular_names(sex)
      students = Student.select {|student| student.sex == sex}
      count = Hash.new(0)
      students.each do |s|
        count[s.first_name] += 1
      end
      puts count
      return count.select { |name, v| name if v == count.values.max }
    end

    
    private
    def get_name_initials(student)
      "#{student.last_name} #{student.first_name[0]}. #{student.middle_name[0]}."
    end

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name, :middle_name, :sex, :age, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/Students.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lab7" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144', skip_pipeline: true %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114', skip_pipeline: true %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72', skip_pipeline: true %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', skip_pipeline: true %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon', skip_pipeline: true %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Lab7</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2022</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Lab7</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Year with most men%", "/year_with_most/men_percentage"  %></li>
            <li><%= link_to "Women students most popular age", "/women_students/most_popular_age"  %></li>
            <li><%= link_to "Women most popular names", "/women_students/most_popular_names"  %></li>
            <li><%= link_to "Men most popular names", "/men_students/most_popular_names"  %></li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>
  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:first_name) %>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :middle_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:middle_name) %>
  </div>
  <div class="form-group">
    <%= f.label :sex, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :sex, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sex) %>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
    <%=f.error_span(:year) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/get_most_popular_names_men.erb
<h2>Students with most popular names(men)</h1>
<ul>
    <%@students.each do |student, _| %>
    <li>
        <%= "#{student}" %>
    </li>
    <% end %>
</ul>

<%= link_to "Back to list", students_path %>

app/views/students/get_most_popular_names_women.erb
<h2>Most popular women names(women)</h1>
<ul>
    <%@students.each do |student, _| %>
    <li>
        <%= "#{student}" %>
    </li>
    <% end %>
</ul>

<%= link_to "Back to list", students_path %>

app/views/students/get_women_students_with_most_popular_age.erb
<h2>Years with most men percentage <%= @percentage %></h1>
<ul>
    <%@students.each do |student| %>
    <li>
        <%= "#{student}" %>
    </li>
    <% end %>
</ul>

<%= link_to "Back to list", students_path %>

app/views/students/get_year_with_most_men_percentage.html.erb
<%if @percentage == 0%>
  <h4>Every year has 0 men percentage</h4>
<% else %>
    <h2>Years with most men percentage <%= @percentage %></h1>
    <ul>
        <%@years_with_percentage.each do |y| %>
        <li>
            <%= "#{y}" %>
        </li>
        <% end %>
    </ul>
<% end %>

<%= link_to "Back to list", students_path %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header" style="margin-left: 50px">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:middle_name) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.last_name %></td>
        <td><%= student.first_name %></td>
        <td><%= student.middle_name %></td>
        <td><%= student.sex %></td>
        <td><%= student.age %></td>
        <td><%= student.year %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Create %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @student.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @student.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:middle_name) %>:</strong></dt>
  <dd><%= @student.middle_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @student.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @student.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @student.year %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>